version: '3.8'

services:
  postgres:
    image: postgres:latest
    container_name: container-postgres
    environment:
      POSTGRES_DB: database
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
